{
 "title": "[AMPR] Nginx Services",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.container.name.keyword\", \"size\": 50}"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "{\"find\": \"terms\", \"field\": \"http_request_method.keyword\", \"size\": 50}"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.container.name:$application AND http_request_method:$method",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP methods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "GET",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "http_request_method.keyword:GET AND kubernetes.container.name:$application",
     "timeField": "@timestamp"
    },
    {
     "alias": "POST",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "http_request_method.keyword:POST AND kubernetes.container.name:$application",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 25, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_request.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.container.name:$application AND http_request_method:$method",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response Codes: ALL",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "response",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.container.name:$application AND http_request_method:$method",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response Codes: ERRORS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "response",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "!http_status: 2* AND !http_status: 3* AND kubernetes.container.name:$application AND http_request_method:$method",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "X-Forwarded-For",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_x_forwarded_for.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.container.name:$application AND http_request_method:$method",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User-Agent",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_user_agent.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.container.name:$application AND http_request_method:$method",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}