{
 "title": "MongoDB Overview",
 "tags": [
  "MongoDB_HA",
  "Percona"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mongodb_up,cluster)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(mongodb_up{cluster=\"$cluster\"},service_name)"
   },
   {
    "name": "shard",
    "label": "Shard Name",
    "query": "label_values(mongodb_mongos_db_collections_total{cluster=\"$cluster\"},shard)"
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
   },
   { "name": "schema", "label": "Schema" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_instance_uptime_seconds{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (service_name) (max_over_time(mongodb_connections{cluster=\"$cluster\",service_name=~\"$service_name\",state=\"current\"}[$interval]) or \nmax_over_time(mongodb_connections{cluster=\"$cluster\",service_name=~\"$service_name\",state=\"current\"}[5m]))"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (sum(rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m]) or rate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m])))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[5m]) > 0))"
    }
   ]
  },
  { "title": "Connections Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Connections",
   "type": "graph",
   "description": "Incoming connections to mongos nodes.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (max_over_time(mongodb_connections{cluster=\"$cluster\"}[$interval]) or max_over_time(mongodb_connections{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "All Operations",
   "type": "graph",
   "description": "Operations are classified by legacy wire protocol type (insert, update, and delete only).",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_op_counters_repl_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_op_counters_repl_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "repl - {{type}}"
    },
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "repl - {{type}}"
    },
    {
     "expr": "avg by (service_name,type) (rate(mongodb_op_counters_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "description": "Docs per second inserted, updated, deleted or returned. (N.b. not 1-to-1 with operation counts.)",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,state) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Cursors",
   "type": "graph",
   "description": "Helps identify why connections are increasing. Shows active cursors compared to cursors being automatically killed after 10 minutes due to an application not closing the connection.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_cursor_open{} or\nmongodb_mongod_cursors{} or\nmongodb_mongos_metrics_cursor_open{} or \nmongodb_mongos_cursors{}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{}[5m])",
     "legendFormat": "moved"
    }
   ]
  }
 ]
}