{
 "title": "K8S Cluster Monitoring",
 "description": "Shows overall cluster stats per Node(s)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "Node", "label": "node", "query": "label_values(node)" }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",instance=~\"^$Node$\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$Node$\"}[1m])) / sum (kube_node_status_capacity_cpu_cores{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/nvme[a-z0-9]*$\",id=\"/\",instance=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/nvme[a-z0-9]*$\",id=\"/\",instance=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_memory_bytes{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity_cpu_cores{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[a-z0-9]*$\",id=\"/\",instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[a-z0-9]*$\",id=\"/\",instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node$\"} and on(pod, namespace) (kube_pod_status_phase{phase=\"Running\"}==1)) by(instance)\r\n) / min(sum(kube_node_status_allocatable_memory_bytes{node=~\"^$Node$\"}) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes{node=~\"^$Node$\"} and on(pod, namespace) (kube_pod_status_phase{phase=\"Running\"}==1)) by(instance)\r\n) / min(sum(kube_node_status_allocatable_memory_bytes{node=~\"^$Node$\"}) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores{node=~\"^$Node$\"} and on(pod, namespace) (kube_pod_status_phase{phase=\"Running\"}==1)) by(instance)\r\n) / min(sum(kube_node_status_allocatable_cpu_cores{node=~\"^$Node$\"}) by (instance)) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ]
    }
   ]
  },
  {
   "title": "Limits",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "max(sum(kube_pod_container_resource_limits_cpu_cores{node=~\"^$Node$\"} and on(pod, namespace) (kube_pod_status_phase{phase=\"Running\"}==1)) by(instance)\r\n) / min(sum(kube_node_status_allocatable_cpu_cores{node=~\"^$Node$\"}) by (instance)) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ]
    }
   ]
  },
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{instance=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Containers CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container!=\"POD\",instance=~\"^$Node$\"}[1m])) by (container, pod)",
     "legendFormat": "pod: {{ pod }} | {{ container }}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",instance=~\"^$Node$\"}[1m])) by (node, name, image)",
     "legendFormat": "docker: {{ node }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{rkt_container!=\"\",instance=~\"^$Node$\"}[1m])) by (node, rkt_container)",
     "legendFormat": "rkt: {{ node }} | {{ rkt_container }}"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Containers memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Containers memory usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container!=\"POD\",instance=~\"^$Node$\"}) by (container, pod)",
     "legendFormat": "pod: {{ pod }} | {{ container }}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",instance=~\"^$Node$\"}) by (node, name, image)",
     "legendFormat": "docker: {{ node }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{rkt_container!=\"\",instance=~\"^$Node$\"}) by (node, rkt_container)",
     "legendFormat": "rkt: {{ node }} | {{ rkt_container }}"
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  { "title": "Containers network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Containers network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}[1m])) by (container, pod)",
     "legendFormat": "-> pod: {{ pod }} | {{ container }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}[1m])) by (container, pod)",
     "legendFormat": "<- pod: {{ pod }} | {{ container }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",instance=~\"^$Node$\"}[1m])) by (node, name, image)",
     "legendFormat": "-> docker: {{ node }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",instance=~\"^$Node$\"}[1m])) by (node, name, image)",
     "legendFormat": "<- docker: {{ node }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{rkt_container!=\"\",instance=~\"^$Node$\"}[1m])) by (node, rkt_container)",
     "legendFormat": "-> rkt: {{ node }} | {{ rkt_container }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{rkt_container!=\"\",instance=~\"^$Node$\"}[1m])) by (node, rkt_container)",
     "legendFormat": "<- rkt: {{ node }} | {{ rkt_container }}"
    }
   ]
  }
 ]
}