{
 "title": "MongoDB WiredTiger",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mongodb_up,cluster)"
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(mongodb_mongod_storage_engine{service_name=~\"$service_name\"}, node_name)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(mongodb_mongod_storage_engine{cluster=~\"$cluster\",engine=\"wiredTiger\"}, service_name)"
   },
   {
    "name": "crop_service",
    "label": "Service Name",
    "query": "label_values(mongodb_up{service_name=~\"$service_name\"}, service_name)"
   },
   {
    "name": "crop_host",
    "label": "Crop Node Name",
    "query": "label_values(mongodb_up{node_name=\"$node_name\"},node_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
   }
  ]
 },
 "panels": [
  {
   "title": "WiredTiger Cache Usage",
   "type": "singlestat",
   "description": "This panel shows the amount of data currently stored in the WiredTiger cache. This data is in its uncompressed format and differs from how the data is stored on disk or in the file system cache. This value will always be lower than the counter shown in the *WiredTiger Max Cache Size* panel.",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_mongod_wiredtiger_cache_bytes{service_name=~\"$service_name\", type=\"total\"})"
    }
   ]
  },
  {
   "title": "WiredTiger Max Cache Size",
   "type": "singlestat",
   "description": "This is the maximum size that the WiredTiger cache can grow to and can be changed from the default value by setting the `storage.wiredTiger.engineConfig.cacheSizeGB` value in the config file or passing in the `--wiredTigerCacheSizeGB` parameter on the command line.\n\nYou can read more about [setting the WiredTiger maximum cache size](https://docs.mongodb.com/manual/reference/configuration-options/#storage.wiredTiger.engineConfig.cacheSizeGB).",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_mongod_wiredtiger_cache_max_bytes{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "WiredTiger Transactions",
   "type": "graph",
   "description": "WiredTiger internal transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_transactions_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Activity",
   "type": "graph",
   "description": "Data volume transfered per second between the WT cache and data files. Writes out always imply disk; Reads are often from OS filebuffer cache already in RAM, but disk if not.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=~\"$service_name\", type=\"read\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=~\"$service_name\", type=\"read\"}[5m]))",
     "legendFormat": "Read into"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=~\"$service_name\", type=\"written\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=~\"$service_name\", type=\"written\"}[5m]))",
     "legendFormat": "Written from"
    }
   ]
  },
  {
   "title": "WiredTiger Block Activity",
   "type": "graph",
   "description": "Data volume handled by the WT block manager per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Sessions",
   "type": "graph",
   "description": "Internal WT storage engine cursors and sessions currently open",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_wiredtiger_session_open_cursors_total{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_session_open_cursors_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Cursors"
    },
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_wiredtiger_session_open_sessions_total{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_session_open_sessions_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "WiredTiger Concurrency Tickets Available",
   "type": "graph",
   "description": "A WT 'ticket' is assigned out for every operation running simultaneously in the WT storage engine. \"Available\" = hardcoded high value - \"Out\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) ((max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{service_name=~\"$service_name\"}[5m])) -\n(max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{service_name=~\"$service_name\"}[5m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "description": "Operations queued due to a lock.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Checkpoint Time",
   "type": "graph",
   "description": "The time spent in WT checkpoint phase. Warning: This calculation averages the cyclical event (default: 1 min) execution to a per-second value.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "current"
    },
    {
     "expr": "avg by (service_name,type) (max_over_time(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Eviction",
   "type": "graph",
   "description": "Least-recently used pages being evicted due to WT cache becoming full.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Pages / sec" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_cache_evicted_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_evicted_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Capacity",
   "type": "graph",
   "description": "Configured max and current size of the WT cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_wiredtiger_cache_max_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_cache_max_bytes{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Max"
    },
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_wiredtiger_cache_bytes{service_name=~\"$service_name\", type=\"total\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_cache_bytes{service_name=~\"$service_name\", type=\"total\"}[5m]))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Pages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (max_over_time(mongodb_mongod_wiredtiger_cache_pages{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_cache_pages{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Operations",
   "type": "graph",
   "description": "WT internal write-ahead log operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_log_operations_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_operations_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Activity",
   "type": "graph",
   "description": "Data volume moved per second in WT internal write-ahead log.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_log_bytes_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_bytes_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Records",
   "type": "graph",
   "description": "Number of records appended per second in WT internal log.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_log_records_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_records_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Changes",
   "type": "graph",
   "description": "Mixed metrics: Docs per second inserted, updated, deleted or returned on any type of node (primary or secondary); + replicated write Ops/sec; + TTL deletes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,state) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"delete\"}[5m]))",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"update\"}[5m]))",
     "legendFormat": "repl_updated"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"insert\"}[5m]))",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "ttl_deleted"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "description": "This panel shows the number of objects (both data (scanned_objects) and index (scanned)) as well as the number of documents that were moved to a new location due to the size of the document growing. Moved documents only apply to the MMAPv1 storage engine.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,state) (rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "description": "Unix or Window memory page faults. Not necessarily from mongodb.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_extra_info_page_faults_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{service_name=~\"$service_name\"}[5m]) or rate(mongodb_extra_info_page_faults_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_extra_info_page_faults_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Faults"
    }
   ]
  }
 ]
}