{
 "title": "MongoDB InMemory",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mongodb_up{environment=~\"$environment\"},cluster)"
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(mongodb_mongod_storage_engine{service_name=~\"$service_name\"}, node_name)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(mongodb_mongod_storage_engine{cluster=~\"$cluster\",engine=\"inMemory\"}, service_name)"
   },
   {
    "name": "crop_service",
    "label": "Service Name",
    "query": "label_values(mongodb_up{service_name=~\"$service_name\"}, service_name)"
   },
   {
    "name": "crop_host",
    "label": "Crop Node Name",
    "query": "label_values(mongodb_up{node_name=\"$node_name\"},node_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
   }
  ]
 },
 "panels": [
  { "title": "MongoDB Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_instance_uptime_seconds{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m]) or rate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[5m]) > 0))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "This shows the number of active connections on the server. Keep in mind the hard limit on the maximum number of connections set by your distribution.\n\nYou can read more about the [connection numbers](https://docs.mongodb.com/manual/administration/analyzing-mongodb-performance/#number-of-connections).",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_connections{service_name=~\"$service_name\", state=\"current\"}[5m]))",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "graph",
   "description": "This shows the number of open cursors for each shard in the cluster. A cursor in MongoDB is a pointer to the result of a given query that can be iterated over. By default a cursor times out after 10 minutes.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,state) (max_over_time(mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\"}[5m]) or\nmax_over_time(mongodb_mongod_cursors{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_cursors{service_name=~\"$service_name\"}[5m]) or\nmax_over_time(mongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\"}[5m]) or\nmax_over_time(mongodb_mongos_cursors{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongos_cursors{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "InMemory Data Size",
   "type": "singlestat",
   "description": "This panel shows the amount of data currently being stored InMemory. This data is in its uncompressed format and differs from how the data is stored on disk or in the file system cache. This value will always be lower than the counter shown in the *InMemory Max Data Size* panel.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_mongod_wiredtiger_cache_bytes{service_name=~\"$service_name\", type=\"total\"})"
    }
   ]
  },
  {
   "title": "InMemory Max Data Size",
   "type": "singlestat",
   "description": "This is the maximum size that the InMemory data can grow to and this value can be changed from the default value by setting the `storage.wiredTiger.inMemory.cacheSizeGB` value in the config file or passing in the `--inMemoryCacheSizeGB` parameter on the command line.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_mongod_wiredtiger_cache_max_bytes{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "InMemory Dirty Pages",
   "type": "singlestat",
   "description": "This panel shows the percentage of InMemory pages that have been changed and not yet had the modified data consolidated.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (avg(mongodb_mongod_wiredtiger_cache_pages{service_name=~\"$service_name\",type=\"dirty\"})/avg(mongodb_mongod_wiredtiger_cache_pages{service_name=~\"$service_name\",type=\"total\"}))"
    }
   ]
  },
  {
   "title": "InMemory Transactions",
   "type": "graph",
   "description": "WiredTiger internal transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_wiredtiger_transactions_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "InMemory Capacity",
   "type": "graph",
   "description": "Configured max and current size of the WiredTiger cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_mongod_wiredtiger_cache_max_bytes{service_name=~\"$service_name\"})",
     "legendFormat": "Maximum"
    },
    {
     "expr": "avg by (service_name) (mongodb_mongod_wiredtiger_cache_bytes{service_name=~\"$service_name\", type=\"total\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "InMemory Sessions",
   "type": "graph",
   "description": "Internal WiredTiger storage engine cursors and sessions currently open.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_mongod_wiredtiger_session_open_cursors_total{service_name=~\"$service_name\"})",
     "legendFormat": "Cursors"
    },
    {
     "expr": "avg by (service_name) (mongodb_mongod_wiredtiger_session_open_sessions_total{service_name=~\"$service_name\"})",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "InMemory Pages",
   "type": "graph",
   "description": "Pages in the WiredTiger cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (mongodb_mongod_wiredtiger_cache_pages{service_name=~\"$service_name\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "InMemory Concurrency Tickets",
   "type": "graph",
   "description": "A WT 'ticket' is assigned out for every operation running simultaneously in the WT storage engine. \"Tickets available\" = hardcoded high value - \"Tickets Out\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{service_name=~\"$service_name\"}-mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{service_name=~\"$service_name\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "description": "Operations queued due to a lock",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Changes",
   "type": "graph",
   "description": "Mixed metrics: Docs per second inserted, updated, deleted or returned on any type of node (primary or secondary); + replicated write Ops/sec; + TTL deletes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,state) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"delete\"}[5m]))",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"update\"}[5m]))",
     "legendFormat": "repl_updated"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"insert\"}[5m]))",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "ttl_deleted"
    }
   ]
  },
  {
   "title": "InMemory Cache Eviction",
   "type": "graph",
   "description": "This panel shows the number of pages that have been evicted from the WiredTiger cache for the given time period. The InMemory storage engine only evicts modified pages which signals a compaction of the data and removal of the dirty pages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Pages / sec" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_wiredtiger_cache_evicted_total{service_name=~\"$service_name\",type=\"modified\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_evicted_total{service_name=~\"$service_name\",type=\"modified\"}[5m]))",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "description": "This panel shows the number of objects (both data (scanned_objects) and index (scanned)) as well as the number of documents that were moved to a new location due to the size of the document growing. Moved documents only apply to the MMAPv1 storage engine.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,state) (rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "description": "Unix or Window memory page faults. Not necessarily from mongodb.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_extra_info_page_faults_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{service_name=~\"$service_name\"}[5m]) or rate(mongodb_extra_info_page_faults_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_extra_info_page_faults_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Faults"
    }
   ]
  }
 ]
}