annotations:
  category: Database
apiVersion: v2
appVersion: 11.11.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 1.x.x
description: CUSTOMIZED CHART
home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
name: postgresql
sources:
- https://github.com/bitnami/bitnami-docker-postgresql
- https://www.postgresql.org/
version: 10.3.9
