{
 "title": "_Home_",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 13, "w": 18, "x": 0, "y": 3 } },
  {
   "title": "MGMT & BTC NFS Storage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes * 100)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kubelet_volume_stats_used_bytes)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kubelet_volume_stats_capacity_bytes)"
    }
   ]
  }
 ]
}