{
 "title": "MQ - Stress Tests",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (Apps)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"gateway-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}[1m])",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"antifraud-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}[1m])",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"blacklist-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}[1m])",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"bin-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}[1m])",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"demo-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}[1m])",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory (Apps)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"gateway-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "container_memory_working_set_bytes{pod=~\"antifraud-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "container_memory_working_set_bytes{pod=~\"blacklist-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "container_memory_working_set_bytes{pod=~\"bin-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "container_memory_working_set_bytes{pod=~\"demo-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage (Services)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"redis-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"metrics\"}[1m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"mongodb-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"metrics\"}[1m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{exported_pod=~\"mongodb-.*\", exported_namespace=\"str\"})",
     "legendFormat": "Limit: Mongo"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{exported_pod=~\"redis-.*\", exported_namespace=\"str\"})",
     "legendFormat": "Limit: Redis"
    }
   ]
  },
  {
   "title": "Memory (Services)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"mongodb-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"metrics\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "container_memory_working_set_bytes{pod=~\"redis-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"metrics\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Throttling (Apps)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"gateway-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}[1m])",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"antifraud-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}[1m])",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"blacklist-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}[1m])",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"bin-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}[1m])",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"demo-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"vault-agent\"}[1m])",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Throttling (Services)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"redis-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"metrics\"}[1m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"mongodb-.*\", namespace=\"str\", image!=\"\", container!=\"POD\", container!=\"metrics\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}