{
 "title": "[ELK] Production websites HTTP access",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP requests / min by vhost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "vhost.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "nginx_type:\"access\" AND env:\"prod\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total HTTP Responses / min by Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\" AND env:\"prod\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "5XX Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\" AND env:\"prod\" AND http_status:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total HTTP requests / min by vhost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "http_request_time", "id": "1", "type": "avg" }
     ],
     "query": "nginx_type:\"access\" AND env:\"prod\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[ btcbit.net ] Total HTTP Responses / min by Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\" AND vhost.keyword:\"btcbit.net\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "5XX Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\" AND vhost.keyword:\"btcbit.net\" AND http_status.keyword:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[ merchant.btcbit.net ] Total HTTP Responses / min by Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\"  AND vhost.keyword:\"merchant.btcbit.net\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "5XX Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\"  AND vhost.keyword:\"merchant.btcbit.net\" AND http_status.keyword:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[ bit-explorer.com ] Total HTTP Responses / min by Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\"  AND vhost.keyword:\"bit-explorer.com\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "5XX Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\"  AND vhost.keyword:\"bit-explorer.com\" AND http_status.keyword:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[ cointic.com ] Total HTTP Responses / min by Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\" AND vhost.keyword:\"cointic.com\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "5XX Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\" AND vhost.keyword:\"cointic.com\" AND http_status.keyword:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[ eazypayz.com ] Total HTTP Responses / min by Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\"  AND vhost.keyword:\"eazypayz.com\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "5XX Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\"  AND vhost.keyword:\"eazypayz.com\" AND http_status.keyword:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[ cryptonezia.com ] Total HTTP Responses / min by Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\"  AND vhost.keyword:\"cryptonezia.com\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "5XX Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "nginx_type:\"access\"  AND vhost.keyword:\"cryptonezia.com\" AND http_status.keyword:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}